---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      focal:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
        umask_value: "027"
platforms:
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: true }"
    memory: 1024
verifier:
  name: ansible
scenario:
  name: single
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
