---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      almalinux8:
        disable_wireless: true
        enable_timesyncd: false
        install_aide: false
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
      almalinux9:
        enable_timesyncd: false
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
      bookworm:
        ansible_become_pass: vagrant
        ansible_python_interpreter: /usr/bin/python3
        disable_wireless: false
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        system_upgrade: false
      focal:
        block_blacklisted: true
        disable_wireless: true
        install_aide: false
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
      jammy:
        disable_ipv6: true
        block_blacklisted: true
        disable_wireless: true
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
platforms:
  - name: almalinux8
    box: almalinux/8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: almalinux9
    box: almalinux/9
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: bookworm
    box: debian/bookworm64
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: true }"
    memory: 1024
  - name: jammy
    box: ubuntu/jammy64
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: true }"
    memory: 1024
verifier:
  name: ansible
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
