---
- name: Disable systemd ctrl-alt-del
  become: true
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: true
    enabled: false
    state: stopped
  when: not ansible_os_family == "RedHat"
  tags:
    - ctrl-alt-del
    - CCE-80785-9
    - systemd

- name: Disable systemd ctrl-alt-del - RedHat family
  become: true
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: true
    enabled: false
    state: stopped
  when: ansible_os_family == "RedHat"
  changed_when: false
  tags:
    - ctrl-alt-del
    - CCE-80785-9
    - systemd
