---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      bookworm:
        ansible_python_interpreter: /usr/bin/python3
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
        system_upgrade: false
      bullseye:
        ansible_become_pass: vagrant
        ansible_python_interpreter: /usr/bin/python3
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
      testing:
        ansible_become_pass: vagrant
        ansible_python_interpreter: /usr/bin/python3
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: vagrant sudo
        suid_sgid_permissions: false
platforms:
  - name: bookworm
    box: bento/debian-12
    instance_raw_config_args:
      - "vbguest.installer_options = { allow_kernel_upgrade: true }"
    memory: 1024
  - name: bullseye
    box: debian/bullseye64
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
  - name: testing
    box: debian/testing64
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
verifier:
  name: ansible
scenario:
  name: debian
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
