---
- name: Configure systemd logind
  become: true
  ansible.builtin.template:
    src: etc/systemd/logind.conf.j2
    dest: /etc/systemd/logind.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  notify:
    - Reload systemd
  tags:
    - systemd
    - logind
