---
- name: Set path
  become: true
  ansible.builtin.lineinfile:
    regexp: ^PATH=
    line: PATH="/usr/local/bin:/usr/sbin:/usr/bin:/bin:/snap/bin"
    dest: /etc/environment
    mode: "0644"
    state: present
    create: false
    backrefs: true
  tags:
    - path
    - M1038

- name: Add path script
  become: true
  ansible.builtin.template:
    src: etc/profile.d/initpath.sh.j2
    dest: /etc/profile.d/initpath.sh
    backup: true
    mode: "0644"
    owner: root
    group: root
  tags:
    - path
    - M1038
